### ISSUE TITLE
Error occurs when including character '&' in homepage url

### ISSUE THREAD

**Issue by kaakaa** [amzn/oss-dashboard#94]
When analysing repository that has `homepage` including multiple query params (e.g. http://example.com?q=1&p=2), I encountered errors.

```
$ bundle exec ruby refresh-dashboard.rb config.yaml
Remaining GitHub Calls: 5000
GitHub rate limit reset: 2017-07-14 15:47:11 +0900
github-sync
 metadata

(snip)

review-source
  kaakaa ....................................................................................................................
generate-dashboard
 xml
  kaakaa
 teams-xml
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:95:in `rescue in parse': #<RuntimeError: Illegal character '&' in raw string "http://example.com/page?q=1&p=2"> (REXML::ParseException)
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/text.rb:155:in `block in check'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/text.rb:153:in `scan'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/text.rb:153:in `check'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/attribute.rb:156:in `element='
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/element.rb:1100:in `[]='
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:35:in `block in parse'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:34:in `each'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:34:in `parse'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/document.rb:287:in `build'
/Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/document.rb:44:in `initialize'
/Users/kaakaa/Documents/github/oss-dashboard/generate-dashboard/generate-dashboard-xml.rb:483:in `new'
/Users/kaakaa/Documents/github/oss-dashboard/generate-dashboard/generate-dashboard-xml.rb:483:in `generate_team_xml'
refresh-dashboard.rb:228:in `block in <main>'
refresh-dashboard.rb:173:in `each'
refresh-dashboard.rb:173:in `<main>'
...
Illegal character '&' in raw string "http://example.com/page?q=1&p=2"
Line: 1952
Position: 96895
Last 80 unconsumed characters:
	from /Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:20:in `parse'
	from /Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/document.rb:287:in `build'
	from /Users/kaakaa/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rexml/document.rb:44:in `initialize'
	from /Users/kaakaa/Documents/github/oss-dashboard/generate-dashboard/generate-dashboard-xml.rb:483:in `new'
	from /Users/kaakaa/Documents/github/oss-dashboard/generate-dashboard/generate-dashboard-xml.rb:483:in `generate_team_xml'
	from refresh-dashboard.rb:228:in `block in <main>'
	from refresh-dashboard.rb:173:in `each'
	from refresh-dashboard.rb:173:in `<main>'
```

I think that It should call `escape_for_xml` for `homepage` element.

**Comment by hyandell** [comment]
Thank you for the fix Yusuke :)
